<script>
  export let size = 32;
  export let color = "undefined";
</script>
{color}<{color}s{color}v{color}g{color}
{color}x{color}m{color}l{color}n{color}s{color}={color}"{color}h{color}t{color}t{color}p{color}:{color}/{color}/{color}w{color}w{color}w{color}.{color}w{color}3{color}.{color}o{color}r{color}g{color}/{color}2{color}0{color}0{color}0{color}/{color}s{color}v{color}g{color}"{color}
{color}w{color}i{color}d{color}t{color}h{color}={color}{{color}s{color}i{color}z{color}e{color}}{color}
{color}h{color}e{color}i{color}g{color}h{color}t{color}={color}{{color}s{color}i{color}z{color}e{color}}{color}
{color}v{color}i{color}e{color}w{color}B{color}o{color}x{color}={color}"{color}0{color}
{color}0{color} {color}3{color}2{color}
{color}3{color}2{color}"{color}>{color}<{color}g{color}
{color}f{color}i{color}l{color}l{color}={color}"{color}n{color}o{color}n{color}e{color}"{color}
{color}f{color}i{color}l{color}l{color}-{color}r{color}u{color}l{color}e{color}={color}"{color}e{color}v{color}e{color}n{color}o{color}d{color}d{color}"{color}>{color}<{color}c{color}i{color}r{color}c{color}l{color}e{color}
{color}c{color}x{color}={color}"{color}1{color}6{color}"{color}
{color}c{color}y{color}={color}"{color}1{color}6{color}"{color}
{color}r{color}={color}"{color}1{color}6{color}"{color}
{color}f{color}i{color}l{color}l{color}={color}"{color}#{color}3{color}0{color}8{color}9{color}F{color}2{color}"{color}/{color}>{color}<{color}p{color}a{color}t{color}h{color}
{color}f{color}i{color}l{color}l{color}={color}"{color}#{color}F{color}F{color}F{color}"{color}
{color}f{color}i{color}l{color}l{color}-{color}r{color}u{color}l{color}e{color}={color}"{color}n{color}o{color}n{color}z{color}e{color}r{color}o{color}"{color}
{color}d{color}={color}"{color}M{color}2{color}1{color}.{color}6{color}2{color}7{color}
{color}1{color}7{color}.{color}8{color}7{color}8{color}c{color}-{color}.{color}4{color}2{color}2{color}.{color}3{color}6{color}3{color}-{color}.{color}8{color}.{color}6{color}8{color}6{color}-{color}1{color}.{color}1{color}7{color}4{color}
{color}1{color}.{color}0{color}1{color}3{color}-{color}.{color}0{color}4{color}2{color}.{color}0{color}3{color}7{color}-{color}.{color}0{color}8{color}4{color}.{color}1{color}0{color}3{color}-{color}.{color}0{color}8{color}4{color}.{color}1{color}5{color}6{color}-{color}.{color}0{color}0{color}6{color}.{color}6{color}3{color}8{color}-{color}.{color}0{color}0{color}4{color}
{color}1{color}.{color}2{color}7{color}5{color}-{color}.{color}0{color}0{color}4{color}
{color}1{color}.{color}9{color}3{color}5{color}.{color}9{color}6{color}1{color}-{color}.{color}4{color}0{color}6{color}
{color}1{color}.{color}4{color}6{color}3{color}-{color}1{color}.{color}6{color}4{color}
{color}1{color}.{color}2{color}6{color}2{color}-{color}3{color}.{color}1{color}0{color}4{color}z{color}m{color}-{color}1{color}.{color}1{color}5{color}8{color}-{color}3{color}.{color}8{color}9{color}7{color}c{color}1{color}.{color}0{color}7{color}1{color}-{color}.{color}6{color}3{color}8{color}
{color}1{color}.{color}1{color}9{color}8{color}-{color}.{color}8{color}5{color}9{color}
{color}1{color}.{color}2{color}0{color}2{color}-{color}2{color}.{color}1{color}2{color}5{color}
{color}0{color}-{color}.{color}1{color}.{color}0{color}0{color}3{color}-{color}.{color}1{color}9{color}9{color}-{color}.{color}0{color}0{color}1{color}-{color}.{color}2{color}9{color}8{color}-{color}.{color}0{color}4{color}6{color}-{color}1{color}.{color}1{color}6{color}3{color}-{color}.{color}8{color}4{color}2{color}-{color}2{color}.{color}1{color}9{color}-{color}1{color}.{color}9{color}4{color}4{color}-{color}2{color}.{color}4{color}3{color}6{color}-{color}.{color}9{color}9{color}-{color}.{color}2{color}2{color}-{color}1{color}.{color}9{color}8{color}8{color}-{color}.{color}4{color}0{color}3{color}-{color}2{color}.{color}9{color}8{color}8{color}-{color}.{color}5{color}7{color}2{color}-{color}.{color}5{color}0{color}9{color}-{color}.{color}0{color}8{color}7{color}-{color}1{color}.{color}0{color}3{color}-{color}.{color}1{color}6{color}1{color}-{color}1{color}.{color}5{color}4{color}3{color}-{color}.{color}1{color}4{color}4{color}-{color}.{color}6{color}2{color}1{color}.{color}0{color}2{color}-{color}1{color}.{color}1{color}2{color}8{color}.{color}3{color}4{color}6{color}-{color}1{color}.{color}5{color}9{color}5{color}.{color}8{color}7{color}8{color}
{color}1{color}.{color}1{color}3{color}2{color}.{color}2{color}1{color}1{color}
{color}2{color}.{color}1{color}8{color}3{color}.{color}4{color}2{color}8{color}
{color}3{color}.{color}2{color}4{color}1{color}.{color}6{color}
{color}1{color}.{color}4{color}5{color}3{color}.{color}2{color}3{color}6{color}
{color}2{color}.{color}5{color}6{color}2{color}.{color}9{color}6{color}5{color}
{color}3{color}.{color}1{color}6{color}8{color}
{color}2{color}.{color}3{color}5{color}4{color}.{color}2{color}3{color}5{color}.{color}5{color}3{color}9{color}.{color}3{color}1{color}
{color}1{color}.{color}1{color}5{color}.{color}4{color}6{color}
{color}1{color}.{color}7{color}4{color}3{color}z{color}m{color}-{color}8{color}.{color}8{color}2{color}3{color}-{color}3{color}.{color}0{color}0{color}8{color}c{color}-{color}.{color}8{color}6{color}.{color}5{color}3{color}4{color}-{color}1{color}.{color}2{color}8{color}4{color}
{color}1{color}.{color}2{color}5{color}8{color}-{color}1{color}.{color}2{color}9{color}7{color}
{color}2{color}.{color}1{color}5{color}8{color}a{color}3{color}2{color}8{color}.{color}0{color}6{color}
{color}3{color}2{color}8{color}.{color}0{color}6{color} {color}0{color}
{color}0{color}0{color}-{color}.{color}0{color}0{color}7{color}
{color}7{color}.{color}2{color}9{color}c{color}.{color}0{color}1{color}
{color}1{color}.{color}1{color}7{color}7{color}.{color}7{color}8{color}7{color}
{color}2{color}.{color}1{color}8{color}6{color}
{color}1{color}.{color}9{color}0{color}9{color}
{color}2{color}.{color}4{color}6{color}.{color}9{color}6{color}.{color}2{color}3{color}4{color}
{color}1{color}.{color}9{color}4{color}2{color}.{color}3{color}7{color}8{color}
{color}2{color}.{color}9{color}1{color}4{color}.{color}5{color}6{color}6{color}.{color}6{color}1{color}6{color}.{color}1{color}2{color}
{color}1{color}.{color}2{color}2{color}6{color}.{color}3{color}0{color}2{color}
{color}1{color}.{color}8{color}6{color}2{color}.{color}1{color}4{color}4{color}.{color}5{color}2{color}-{color}.{color}1{color}3{color}.{color}9{color}8{color}4{color}-{color}.{color}3{color}4{color}9{color}
{color}1{color}.{color}3{color}5{color}-{color}.{color}8{color}6{color}3{color}-{color}1{color}.{color}1{color}6{color}6{color}-{color}.{color}2{color}1{color}9{color}-{color}2{color}.{color}2{color}6{color}1{color}-{color}.{color}4{color}6{color}-{color}3{color}.{color}3{color}6{color}7{color}-{color}.{color}6{color}2{color}4{color}-{color}1{color}.{color}8{color}9{color}3{color}-{color}.{color}2{color}8{color}1{color}-{color}3{color}.{color}3{color}6{color}1{color}-{color}1{color}.{color}9{color}5{color}8{color}-{color}3{color}.{color}3{color}6{color}3{color}-{color}3{color}.{color}9{color}1{color}-{color}.{color}0{color}0{color}3{color}-{color}2{color}.{color}2{color}3{color}2{color}-{color}.{color}0{color}0{color}1{color}-{color}4{color}.{color}4{color}6{color}3{color}-{color}.{color}0{color}0{color}1{color}-{color}6{color}.{color}6{color}9{color}5{color}v{color}-{color}.{color}5{color}2{color}6{color}z{color}m{color}1{color}.{color}3{color}3{color}8{color}-{color}.{color}3{color}5{color}1{color}c{color}-{color}.{color}0{color}1{color}2{color}.{color}2{color}4{color}7{color}-{color}.{color}0{color}3{color}.{color}4{color}3{color}1{color}-{color}.{color}0{color}3{color}.{color}6{color}1{color}5{color}a{color}2{color}5{color}2{color}2{color}.{color}2{color}6{color}
{color}2{color}5{color}2{color}2{color}.{color}2{color}6{color} {color}0{color}
{color}0{color}0{color}0{color}
{color}6{color}.{color}7{color}3{color}8{color}c{color}.{color}0{color}0{color}3{color}
{color}1{color}.{color}4{color}7{color}6{color}.{color}8{color}9{color}5{color}
{color}2{color}.{color}5{color}3{color}6{color}
{color}2{color}.{color}3{color}1{color}2{color}
{color}2{color}.{color}7{color}8{color}4{color}
{color}1{color}.{color}0{color}2{color}4{color}.{color}1{color}8{color}
{color}2{color}.{color}0{color}4{color}4{color}.{color}3{color}8{color}
{color}3{color}.{color}0{color}6{color}6{color}.{color}5{color}7{color}.{color}0{color}7{color}1{color}.{color}0{color}1{color}3{color}.{color}1{color}4{color}3{color}.{color}0{color}2{color}.{color}2{color}1{color}5{color}.{color}0{color}2{color}8{color}.{color}4{color}8{color}5{color}.{color}0{color}5{color}4{color}.{color}5{color}0{color}2{color}.{color}0{color}4{color}5{color}.{color}5{color}0{color}5{color}-{color}.{color}4{color}4{color}1{color}.{color}0{color}0{color}5{color}-{color}.{color}7{color}4{color}5{color}-{color}.{color}0{color}2{color}-{color}1{color}.{color}4{color}9{color}.{color}0{color}1{color}5{color}-{color}2{color}.{color}2{color}3{color}3{color}.{color}0{color}1{color}-{color}.{color}2{color}2{color}.{color}1{color}2{color}1{color}-{color}.{color}4{color}9{color}7{color}.{color}2{color}8{color}-{color}.{color}6{color}3{color}8{color}.{color}8{color}1{color}1{color}-{color}.{color}7{color}2{color}3{color}
{color}1{color}.{color}6{color}5{color}3{color}-{color}1{color}.{color}4{color}1{color}
{color}2{color}.{color}4{color}8{color}4{color}-{color}2{color}.{color}1{color}1{color}.{color}2{color}2{color}6{color}-{color}.{color}1{color}9{color}.{color}4{color}5{color}8{color}-{color}.{color}3{color}2{color}.{color}7{color}6{color}2{color}-{color}.{color}1{color}7{color}3{color}.{color}3{color}2{color}1{color}.{color}1{color}5{color}5{color}.{color}4{color}0{color}5{color}.{color}4{color}2{color}3{color}.{color}4{color}.{color}7{color}6{color}-{color}.{color}0{color}1{color}2{color}.{color}8{color}4{color}4{color}.{color}0{color}0{color}6{color}
{color}1{color}.{color}6{color}8{color}9{color}-{color}.{color}0{color}2{color}
{color}2{color}.{color}5{color}3{color}1{color}-{color}.{color}0{color}4{color}9{color}
{color}1{color}.{color}5{color}2{color}2{color}-{color}1{color}.{color}1{color}5{color}3{color}
{color}3{color}.{color}0{color}2{color}-{color}2{color}.{color}5{color}7{color}
{color}3{color}.{color}5{color}a{color}.{color}9{color}3{color}8{color}.{color}9{color}3{color}8{color}
{color}0{color}
{color}0{color}0{color}-{color}.{color}5{color}6{color}.{color}4{color}7{color}c{color}-{color}.{color}8{color}7{color}3{color}
{color}1{color}.{color}5{color}5{color}-{color}2{color}.{color}3{color}6{color}9{color}
{color}2{color}.{color}1{color}4{color}8{color}-{color}3{color}.{color}9{color}7{color}2{color}
{color}1{color}.{color}9{color}3{color}6{color}-{color}1{color}.{color}3{color}1{color}4{color}-{color}.{color}1{color}7{color}5{color}-{color}2{color}.{color}6{color}1{color}8{color}-{color}.{color}4{color}5{color}2{color}-{color}3{color}.{color}9{color}1{color}6{color}-{color}.{color}7{color}3{color}-{color}1{color}.{color}6{color}7{color}2{color}-{color}.{color}3{color}5{color}8{color}-{color}2{color}.{color}9{color}0{color}7{color}-{color}1{color}.{color}9{color}1{color}4{color}-{color}2{color}.{color}9{color}3{color}4{color}-{color}3{color}.{color}7{color}7{color}6{color}-{color}.{color}0{color}3{color}6{color}-{color}2{color}.{color}5{color}0{color}6{color}-{color}.{color}0{color}2{color}4{color}-{color}5{color}.{color}0{color}1{color}3{color}.{color}0{color}1{color}9{color}-{color}7{color}.{color}5{color}1{color}8{color}.{color}0{color}2{color}6{color}-{color}1{color}.{color}5{color}6{color}6{color}
{color}1{color}.{color}1{color}9{color}-{color}3{color}.{color}0{color}2{color}
{color}2{color}.{color}6{color}6{color}6{color}-{color}3{color}.{color}5{color}a{color}.{color}7{color}7{color}6{color}.{color}7{color}7{color}6{color}
{color}0{color}
{color}0{color}0{color}.{color}3{color}9{color}4{color}-{color}.{color}3{color}2{color}5{color}c{color}.{color}9{color}9{color}-{color}1{color}.{color}7{color}1{color}8{color}
{color}2{color}.{color}5{color}9{color}8{color}-{color}2{color}.{color}4{color}1{color}5{color}
{color}4{color}.{color}5{color}0{color}9{color}-{color}1{color}.{color}9{color}8{color}7{color}
{color}1{color}.{color}0{color}6{color}.{color}2{color}3{color}7{color}
{color}2{color}.{color}1{color}3{color}9{color}.{color}3{color}9{color}3{color}
{color}3{color}.{color}2{color}0{color}5{color}.{color}6{color}1{color}
{color}1{color}.{color}8{color}9{color}2{color}.{color}3{color}8{color}6{color}
{color}3{color}.{color}1{color}5{color}6{color}
{color}1{color}.{color}9{color}4{color}8{color}
{color}3{color}.{color}1{color}8{color}1{color}
{color}3{color}.{color}9{color}1{color}4{color}.{color}0{color}0{color}7{color}.{color}5{color}5{color}9{color}.{color}0{color}1{color}1{color}
{color}1{color}.{color}1{color}1{color}8{color}-{color}.{color}0{color}2{color}
{color}1{color}.{color}6{color}7{color}5{color}-{color}.{color}0{color}0{color}9{color}.{color}1{color}7{color}7{color}-{color}.{color}0{color}8{color}7{color}.{color}4{color}0{color}3{color}-{color}.{color}2{color}1{color}3{color}.{color}5{color}1{color}4{color}-{color}.{color}9{color}0{color}7{color}.{color}8{color}-{color}1{color}.{color}8{color}2{color}5{color}
{color}1{color}.{color}5{color}8{color}8{color}-{color}2{color}.{color}7{color}6{color}6{color}
{color}2{color}.{color}3{color}4{color}6{color}-{color}.{color}1{color}4{color}5{color}.{color}1{color}1{color}7{color}-{color}.{color}4{color}7{color}.{color}1{color}4{color}4{color}-{color}.{color}6{color}3{color}2{color}.{color}0{color}5{color}7{color}-{color}.{color}1{color}5{color}9{color}-{color}.{color}0{color}8{color}6{color}-{color}.{color}2{color}9{color}3{color}-{color}.{color}3{color}6{color}5{color}-{color}.{color}3{color}0{color}4{color}-{color}.{color}5{color}6{color}7{color}-{color}.{color}0{color}3{color}9{color}-{color}.{color}6{color}6{color}7{color}.{color}0{color}3{color}5{color}-{color}1{color}.{color}3{color}4{color}4{color}-{color}.{color}0{color}3{color}-{color}2{color}.{color}0{color}0{color}7{color}-{color}.{color}1{color}3{color}-{color}1{color}.{color}3{color}2{color}9{color}-{color}1{color}.{color}0{color}3{color}5{color}-{color}2{color}.{color}2{color}0{color}7{color}-{color}2{color}.{color}3{color}9{color}9{color}-{color}2{color}.{color}4{color}3{color}4{color}-{color}1{color}.{color}0{color}8{color}4{color}-{color}.{color}1{color}8{color}-{color}2{color}.{color}1{color}6{color}6{color}-{color}.{color}3{color}7{color}5{color}-{color}3{color}.{color}2{color}4{color}9{color}-{color}.{color}5{color}6{color}1{color}-{color}.{color}1{color}1{color}6{color}-{color}.{color}0{color}2{color}-{color}.{color}2{color}3{color}4{color}-{color}.{color}0{color}2{color}9{color}-{color}.{color}3{color}9{color}8{color}-{color}.{color}0{color}4{color}8{color}z{color}"{color}/{color}>{color}<{color}/{color}g{color}>{color}<{color}/{color}s{color}v{color}g{color}>{color}
